export interface CommandSuggestion {
  command: string;
  description: string;
}

export const commands: CommandSuggestion[] = [
  { command: '/a (mensagem)', description: 'Envia mensagem no chat administrativo' },
  { command: '/aabastecer', description: 'Abastece um veículo' },
  { command: '/aarmazenamento', description: 'Visualiza o armazenamento de uma propriedade' },
  { command: '/aarmazenamentos', description: 'Abre o painel de gerenciamento de armazenamentos' },
  { command: '/abastecer (porcentagem)', description: 'Abastece um veículo em um posto de combustível' },
  { command: '/ac (tipo)', description: 'Aceita um convite' },
  { command: '/acaminhoneiro', description: 'Abre o painel de gerenciamento de localizações de caminhoneiros' },
  { command: '/aceitar (tipo)', description: 'Aceita um convite' },
  { command: '/aceitarck', description: 'Aceita o CK no personagem' },
  { command: '/aceitarhospital', description: 'Aceita o tratamento médico após estar ferido e é levado ao hospital' },
  { command: '/acurar (ID ou nome)', description: 'Cura um personagem ferido' },
  { command: '/adanos (veículo)', description: 'Visualiza os danos de um veículo' },
  { command: '/adduniforme (nome)', description: 'Cria um uniforme com as roupas que está vestindo' },
  { command: '/admins', description: 'Exibe os administradores do servidor' },
  { command: '/ado (mensagem)', description: 'Interpretação do ambiente' },
  { command: '/aduty', description: 'Entra/sai de serviço administrativo' },
  { command: '/aequipamentos', description: 'Abre o painel de gerenciamento de equipamentos' },
  { command: '/aestacionar (veículo)', description: 'Estaciona um veículo' },
  { command: '/aferimentos (ID ou nome)', description: 'Visualiza os ferimentos de um personagem' },
  { command: '/ainfos', description: 'Gerencia todas marcas de informações' },
  { command: '/ajail (ID ou nome) (minutos) (motivo)', description: 'Prende um personagem online administrativamente' },
  { command: '/ajuda', description: 'Exibe os comandos do servidor' },
  { command: '/algemar (ID ou nome)', description: 'Algema/desalgema um personagem' },
  { command: '/alteracoesplaca', description: 'Lista as solicitações de alterações de placa' },
  { command: '/alterarnumero (número)', description: 'Altera o número do seu celular equipado' },
  { command: '/alugarempresa', description: 'Aluga uma empresa' },
  { command: '/ame (mensagem)', description: 'Interpretação de ações de um personagem' },
  { command: '/amotor', description: 'Liga/desliga o motor de um veículo' },
  { command: '/an (mensagem)', description: 'Envia um anúncio' },
  { command: '/anuncios', description: 'Exibe os anúncios em andamento' },
  { command: '/apreender (id) (valor) (dias) (motivo)', description: 'Apreende um veículo' },
  { command: '/aprovarplaca (placa)', description: 'Aprova uma alteração de placa' },
  { command: '/arecolhercorpo', description: 'Envia um corpo para o necrotério' },
  { command: '/aremovercorpo', description: 'Remove um corpo' },
  { command: '/areparar (veículo)', description: 'Conserta um veículo' },
  { command: '/armac', description: 'Altera posicionamento da arma acoplada ao corpo' },
  { command: '/armacorpo', description: 'Altera posicionamento da arma acoplada ao corpo' },
  { command: '/armazenamento', description: 'Visualiza o armazenamento de uma propriedade' },
  { command: '/arrombar', description: 'Arromba a porta de uma propriedade' },
  { command: '/at (ID)', description: 'Atende um SOS/report' },
  { command: '/atcha (chamada)', description: 'Atende uma chamada' },
  { command: '/atender', description: 'Atende a ligação' },
  { command: '/atm', description: 'Gerencia sua conta bancária em uma ATM' },
  { command: '/atrabalho', description: 'Entra/sai de serviço administrativo' },
  { command: '/atunar', description: 'Realiza modificações em um veículo' },
  { command: '/autobaixo', description: 'Ativa/desativa mensagens em tom baixo automaticamente' },
  { command: '/aveiculo (modelo)', description: 'Cria um veículo temporário' },
  { command: '/aviso (ID ou nome) (motivo)', description: 'Aplica um aviso em um personagem online' },
  { command: '/b (mensagem)', description: 'Chat OOC local' },
  { command: '/baixo (mensagem)', description: 'Fala baixo' },
  { command: '/ban (ID ou nome) (dias [0 para permanente]) (motivo)', description: 'Bane um jogador' },
  { command: '/blockf', description: 'Bloqueia/desbloqueia o chat OOC da facção' },
  { command: '/bocafumo', description: 'Usa uma boca de fumo' },
  { command: '/bocasfumo', description: 'Abre o painel de gerenciamento de bocas de fumo' },
  { command: '/boombox', description: 'Altera as configurações de uma boombox' },
  { command: '/booster', description: 'Obtem recompensa por boostar o Discord principal do servidor' },
  { command: '/br (tipo)', description: 'Cria uma barreira' },
  { command: '/caminhada (tipo)', description: 'Altera o estilo de caminhada' },
  { command: '/canal (slot [1-5]) (canal)', description: 'Troca os canais de rádio' },
  { command: '/cancelarcaixas', description: 'Devolve as caixas da rota' },
  { command: '/cancelarconvite (ID ou nome) (tipo)', description: 'Cancela um convite' },
  { command: '/capo', description: 'Abre/fecha o capô de um veículo' },
  { command: '/carregar (ID ou nome)', description: 'Carrega um jogador' },
  { command: '/carregarcaixas', description: 'Carrega o seu veículo com as caixas da rota' },
  { command: '/cc (tipo)', description: 'Cancela um convite' },
  { command: '/cel', description: 'Abre o celular' },
  { command: '/celular', description: 'Abre o celular' },
  { command: '/chamadas', description: 'Exibe as chamadas aguardando resposta' },
  { command: '/checar (ID ou nome)', description: 'Visualiza as informações de um personagem' },
  { command: '/checarveh (veículo)', description: 'Visualiza o proprietário de um veículo' },
  { command: '/cinto', description: 'Coloca/retira o cinto de segurança' },
  { command: '/colocar (ID ou nome) (assento (1-3))', description: 'Coloca um jogador em um veículo' },
  { command: '/colocarlixo', description: 'Coloca um saco de lixo em um caminhão de lixo' },
  { command: '/colocarpregos (tamanho (1-3))', description: 'Coloca um tapete de pregos no chão' },
  { command: '/comprar', description: 'Compra uma propriedade' },
  { command: '/concessionarias', description: 'Abre o painel de gerenciamento de concessionárias' },
  { command: '/config', description: 'Exibe as suas configurações' },
  { command: '/configuracoes', description: 'Exibe as suas configurações' },
  { command: '/confisco', description: 'Cria um registro de confisco' },
  { command: '/contrabandistas', description: 'Abre o painel de gerenciamento de contrabandistas' },
  { command: '/contrabando (quantidade)', description: 'Vende itens para um contrabandista' },
  { command: '/corpoferimentos', description: 'Visualiza os ferimentos de um corpo' },
  { command: '/corpoinv', description: 'Abre o inventário de um corpo' },
  { command: '/cprop (interior) (valor)', description: 'Cria uma propriedade' },
  { command: '/creport (ID)', description: 'Converte um report para SOS' },
  { command: '/criarpropriedade (interior) (valor)', description: 'Cria uma propriedade' },
  { command: '/criaruniforme (nome)', description: 'Cria um uniforme através do menu de seleção' },
  { command: '/cs (mensagem)', description: 'Sussura para todos no veículo' },
  { command: '/csos (ID)', description: 'Converte um SOS para report' },
  { command: '/curar (ID ou nome)', description: 'Cura um personagem ferido' },
  { command: '/cw (mensagem)', description: 'Sussura para todos no veículo' },
  { command: '/dados (2-20)', description: 'Joga um dado cujo o resultado será um número aleatório' },
  { command: '/danos (veículo)', description: 'Visualiza os danos de um veículo' },
  { command: '/daritem', description: 'Dá um item para um personagem' },
  { command: '/deluniforme (nome)', description: 'Remove um uniforme' },
  { command: '/dep (mensagem)', description: 'Fala no canal interdepartamental' },
  { command: '/desem (palavra)', description: 'Desembaralha uma palavra da ligação direta em um veículo' },
  { command: '/desembaralhar (palavra)', description: 'Desembaralha uma palavra da ligação direta em um veículo' },
  { command: '/desmanchar', description: 'Desmancha um veículo' },
  { command: '/dl', description: 'Ativa/desativa o DL' },
  { command: '/do (mensagem)', description: 'Interpretação do ambiente' },
  { command: '/doa (mensagem)', description: 'Interpretação do ambiente com metade do dobro normal' },
  { command: '/doalto (mensagem)', description: 'Interpretação do ambiente com metade do dobro normal' },
  { command: '/doar (quantidade)', description: 'Remove a quantidade de dinheiro especificada' },
  { command: '/dob (mensagem)', description: 'Interpretação do ambiente com metade do range normal' },
  { command: '/dobaixo (mensagem)', description: 'Interpretação do ambiente com metade do range normal' },
  { command: '/drogas', description: 'Abre o painel de gerenciamento de drogas' },
  { command: '/duty', description: 'Entra/sai de serviço' },
  { command: '/animacoes', description: 'Abre o painel de animações' },
  { command: '/emprego', description: 'Pega um emprego' },
  { command: '/empregos', description: 'Abre o painel de gerenciamento de empregos' },
  { command: '/empresa', description: 'Gerencia suas empresas' },
  { command: '/empresas', description: 'Abre o painel de gerenciamento de empresas' },
  { command: '/entregarcaixas', description: 'Entrega as caixas da rota em um ponto de entrega' },
  { command: '/equipar (nome [lista])', description: 'Pega equipamentos' },
  { command: '/f (mensagem)', description: 'Chat OOC da facção' },
  { command: '/faccao', description: 'Abre o painel de gerenciamento da facção' },
  { command: '/faccoes', description: 'Abre o painel de gerenciamento de facções' },
  { command: '/farmazenamento', description: 'Usa o armazenamento da facção' },
  { command: '/ferimentos (ID ou nome)', description: 'Visualiza os ferimentos de um personagem' },
  { command: '/fontsize (tamanho)', description: 'Altera o tamanho da fonte do chat' },
  { command: '/freparar', description: 'Conserta veículos da facção' },
  { command: '/g (mensagem)', description: 'Grita' },
  { command: '/gov (mensagem)', description: 'Envia um anúncio governamental da facção' },
  { command: '/grafitar', description: 'Inicia um grafite' },
  { command: '/grafites', description: 'Gerencia os grafites' },
  { command: '/helif', description: 'Congela/descongela um helicóptero' },
  { command: '/historicocriminal', description: 'Visualiza o histórico criminal do seu personagem' },
  { command: '/horas', description: 'Exibe o horário' },
  { command: '/hotwire', description: 'Faz ligação direta em um veículo' },
  { command: '/hq (mensagem)', description: 'Envia uma mensagem no rádio da facção como dispatcher' },
  { command: '/hs (mensagem)', description: 'Envia mensagem no chat head staff' },
  { command: '/id', description: 'Procura o ID de um personagem' },
  { command: '/infos', description: 'Gerencia suas marcas de informações' },
  { command: '/int (tipo)', description: 'Visualiza um tipo de interior' },
  { command: '/ir (ID ou nome)', description: 'Vai a um personagem' },
  { command: '/irveh (veículo)', description: 'Vai a um veículo' },
  { command: '/itens', description: 'Abre o painel de gerenciamento de itens' },
  { command: '/janela (opção [fe, fd, te, td, todas])', description: 'Abre/fecha a janela de um veículo' },
  { command: '/janelas (opção [fe, fd, te, td, todas])', description: 'Abre/fecha a janela de um veículo' },
  { command: '/ja (opção [fe, fd, te, td, todas])', description: 'Abre/fecha a janela de um veículo' },
  { command: '/kick (ID ou nome) (motivo)', description: 'Expulsa um personagem' },
  { command: '/levantar (ID ou nome)', description: 'Levanta um jogador gravemente ferido somente de socos' },
  { command: '/ligacaodireta', description: 'Faz ligação direta em um veículo' },
  { command: '/ligar (número ou nome do contato)', description: 'Liga para um número' },
  { command: '/limparchat', description: 'Limpa o seu chat' },
  { command: '/limparchatgeral', description: 'Limpa o chat de todos os personagens' },
  { command: '/listasos', description: 'Lista os SOS pendentes' },
  { command: '/lsp (usuário) (quantidade)', description: 'Adiciona LS Points para um usuário' },
  { command: '/meg (mensagem)', description: 'Fala no megafone' },
  { command: '/maquiagem', description: 'Edita sua maquiagem' },
  { command: '/mdc', description: 'Abre o MDC' },
  { command: '/me (mensagem)', description: 'Interpretação de ações de um personagem' },
  { command: '/mea (mensagem)', description: 'Interpretação de ações de um personagem com dobro do range normal' },
  { command: '/mealto (mensagem)', description: 'Interpretação de ações de um personagem com dobro do range normal' },
  { command: '/meb (mensagem)', description: 'Interpretação de ações de um personagem com metade do range normal' },
  { command: '/mebaixo (mensagem)', description: 'Interpretação de ações de um personagem com metade do range normal' },
  { command: '/mic', description: 'Fala em um microfone' },
  { command: '/ml (ID ou nome)', description: 'Mostra a licença de motorista para um personagem' },
  { command: '/mobilias', description: 'Gerencia as mobílias de uma propriedade' },
  { command: '/modofoto', description: 'Ativa/desativa o modo foto' },
  { command: '/moeda', description: 'Joga uma moeda cujo o resultado será cara ou coroa' },
  { command: '/mostrardistintivo (ID ou nome)', description: 'Mostra seu distintivo para um personagem' },
  { command: '/mostrarid (ID ou nome)', description: 'Mostra a identidade para um personagem' },
  { command: '/mostraridentidade (ID ou nome)', description: 'Mostra a identidade para um personagem' },
  { command: '/mostrarlicenca (ID ou nome)', description: 'Mostra a licença de motorista para um personagem' },
  { command: '/motor', description: 'Liga/desliga o motor de um veículo' },
  { command: '/ooc (mensagem)', description: 'Chat OOC Global' },
  { command: '/objetos', description: 'Abre o painel de gerenciamento de objetos' },
  { command: '/p (ID ou nome) (mensagem)', description: 'Fala destinada a uma pessoa' },
  { command: '/pagar (ID ou nome) (quantidade)', description: 'Entrega dinheiro para um personagem próximo' },
  { command: '/pagesize (tamanho)', description: 'Altera a quantidade de linhas do chat' },
  { command: '/para (ID ou nome) (mensagem)', description: 'Fala destinada a uma pessoa' },
  { command: '/parabaixo (ID ou nome) (mensagem)', description: 'Fala baixo destinado a uma pessoa' },
  { command: '/paragritar (ID ou nome) (mensagem)', description: 'Grito destinado a uma pessoa' },
  { command: '/pb (ID ou nome) (mensagem)', description: 'Fala baixo destinado a uma pessoa' },
  { command: '/pboombox', description: 'Altera as configurações de uma saída de áudio da propriedade' },
  { command: '/pchave', description: 'Cria uma chave cópia de uma propriedade' },
  { command: '/pegarlixo', description: 'Pega um saco de lixo em um ponto de coleta' },
  { command: '/pegarpregos', description: 'Pega um tapete de pregos do chão' },
  { command: '/pfechadura', description: 'Altera a fechadura de uma propriedade' },
  { command: '/pg (ID ou nome) (mensagem)', description: 'Grito destinado a uma pessoa' },
  { command: '/phora (hora)', description: 'Altera o horário da propriedade' },
  { command: '/picklock', description: 'Quebra a trava de um veículo' },
  { command: '/pliberar', description: 'Libera uma propriedade roubada' },
  { command: '/pm (ID ou nome) (mensagem)', description: 'Envia uma mensagem privada' },
  { command: '/portamalas (opção [abrir, fechar, ver])', description: 'Gerencia o porta-malas de um veículo' },
  { command: '/portas', description: 'Abre o painel de gerenciamento de portas' },
  { command: '/pos (x) (y) (z)', description: 'Vai até a posição' },
  { command: '/premium', description: 'Abre o painel de gerenciamento Premium' },
  { command: '/propnoclip', description: 'Ativa/desativa a câmera livre para mobiliar' },
  { command: '/proximo (distância)', description: 'Lista os itens que estão próximos' },
  { command: '/prox (distância)', description: 'Lista os itens que estão próximos' },
  { command: '/ptempo (tempo)', description: 'Altera o tempo da propriedade' },
  { command: '/ptime (hora)', description: 'Altera o horário da propriedade' },
  { command: '/pupgrade', description: 'Realiza atualições na propriedade' },
  { command: '/pvender (ID ou nome) (valor)', description: 'Vende uma propriedade para um personagem' },
  { command: '/pvendergoverno', description: 'Venda uma propriedade para o governo' },
  { command: '/pweather (tempo)', description: 'Altera o tempo da propriedade' },
  { command: '/quebrartrava', description: 'Quebra a trava de um veículo' },
  { command: '/r (mensagem)', description: 'Fala no canal de rádio 1' },
  { command: '/r2 (mensagem)', description: 'Fala no canal de rádio 2' },
  { command: '/r3 (mensagem)', description: 'Fala no canal de rádio 3' },
  { command: '/r4 (mensagem)', description: 'Fala no canal de rádio 4' },
  { command: '/r5 (mensagem)', description: 'Fala no canal de rádio 5' },
  { command: '/radar (velocidade)', description: 'Coloca um radar de velocidade' },
  { command: '/radaroff', description: 'Remove um radar de velocidade' },
  { command: '/rajail (nome do personagem)', description: 'Solta um personagem da prisão administrativa' },
  { command: '/rapel', description: 'Desce de rapel dos assentos traseiros de um helicóptero apropriado' },
  { command: '/raviso (nome do personagem)', description: 'Remove o aviso mais recente de um personagem' },
  { command: '/rb', description: 'Remove uma barreira' },
  { command: '/rbaixo (mensagem)', description: 'Fala baixo no canal de rádio 1' },
  { command: '/rbaixo2 (mensagem)', description: 'Fala baixo no canal de rádio 2' },
  { command: '/rbaixo3 (mensagem)', description: 'Fala baixo no canal de rádio 3' },
  { command: '/rbaixo4 (mensagem)', description: 'Fala baixo no canal de rádio 4' },
  { command: '/rbaixo5 (mensagem)', description: 'Fala baixo no canal de rádio 5' },
  { command: '/rball', description: 'Remove todas barreiras' },
  { command: '/rballme', description: 'Remove todas barreiras criadas por você' },
  { command: '/rc (tipo)', description: 'Recusa um convite' },
  { command: '/rdo (mensagem)', description: 'Interpretação do ambiente no canal de rádio 1' },
  { command: '/rdo2 (mensagem)', description: 'Interpretação do ambiente no canal de rádio 2' },
  { command: '/rdo3 (mensagem)', description: 'Interpretação do ambiente no canal de rádio 3' },
  { command: '/rdo4 (mensagem)', description: 'Interpretação do ambiente no canal de rádio 4' },
  { command: '/rdo5 (mensagem)', description: 'Interpretação do ambiente no canal de rádio 5' },
  { command: '/re (mensagem)', description: 'Responde a última mensagem privada recebida' },
  { command: '/rebocar (veículo)', description: 'Rebocar um veículo' },
  { command: '/rebocaroff', description: 'Solta um veículo' },
  { command: '/recolhercorpo', description: 'Envia um corpo para o necrotério' },
  { command: '/recusar (tipo)', description: 'Recusa um convite' },
  { command: '/reparar', description: 'Conserta um veículo na central de mecânicos quando não há mecânicos em serviço' },
  { command: '/reportar (mensagem)', description: 'Envia um report aos administradores em serviço' },
  { command: '/reprovarplaca (placa)', description: 'Reprova uma alteração de placa' },
  { command: '/retirar (ID ou nome)', description: 'Retira um jogador de um veículo' },
  { command: '/revistar (ID ou nome)', description: 'Solicita uma revista em um personagem' },
  { command: '/rgrafite', description: 'Remove um grafite de sua autoria' },
  { command: '/rme (mensagem)', description: 'Interpretação de ações de um personagem no canal de rádio 1' },
  { command: '/rme2 (mensagem)', description: 'Interpretação de ações de um personagem no canal de rádio 2' },
  { command: '/rme3 (mensagem)', description: 'Interpretação de ações de um personagem no canal de rádio 3' },
  { command: '/rme4 (mensagem)', description: 'Interpretação de ações de um personagem no canal de rádio 4' },
  { command: '/rme5 (mensagem)', description: 'Interpretação de ações de um personagem no canal de rádio 5' },
  { command: '/rotas', description: 'Exibe as rotas disponíveis para trabalho' },
  { command: '/roubarpropriedade', description: 'Rouba uma propriedade' },
  { command: '/s (ID ou nome) (mensagem)', description: 'Sussura' },
  { command: '/sa', description: 'Para as animações' },
  { command: '/sairemprego', description: 'Sai do emprego' },
  { command: '/sairfaccao', description: 'Sai da facção' },
  { command: '/save', description: 'Exibe sua posição e rotação ou do seu veículo no console (F8)' },
  { command: '/sc (mensagem)', description: 'Envia mensagem no chat support' },
  { command: '/setdep (departamento [lista])', description: 'Define qual o departamento de destino no canal interdepartamental' },
  { command: '/sms (número ou nome do contato) (mensagem)', description: 'Envia um SMS' },
  { command: '/soltar', description: 'Para de carregar um jogador' },
  { command: '/sos (mensagem)', description: 'Envia uma dúvida' },
  { command: '/spec (ID ou nome)', description: 'Observa um personagem' },
  { command: '/specoff', description: 'Para de observar um personagem' },
  { command: '/specs', description: 'Lista quem está observando um personagem' },
  { command: '/stats', description: 'Exibe as informações do seu personagem' },
  { command: '/stopanim', description: 'Para as animações' },
  { command: '/sa', description: 'Para as animações' },
  { command: '/t (mensagem)', description: 'Fala em uma transmissão se possuir permissão' },
  { command: '/tela', description: 'Exibe um fundo com a cor de fundo configurada na tela' },
  { command: '/tempo (tempo) (temperatura)', description: 'Define um tempo e temperatura fixos' },
  { command: '/timestamp', description: 'Ativa/desativa o timestamp' },
  { command: '/tp (ID ou nome) (ID ou nome)', description: 'Teleporta um personagem para outro' },
  { command: '/tplayer (ID ou nome)', description: 'Convida/expulsa alguém para uma transmissão' },
  { command: '/trabalho', description: 'Entra/sai de serviço' },
  { command: '/vertransmissao', description: 'Acompanha/para de acompanhar uma transmissão' },
  { command: '/transmissao', description: 'Inicia/para uma transmissão' },
  { command: '/trazer (ID ou nome)', description: 'Traz um personagem' },
  { command: '/trazerveh (veículo)', description: 'Traz um veículo' },
  { command: '/trocarpersonagem', description: 'Desconecta do personagem atual e abre a seleção de personagens' },
  { command: '/tv', description: 'Altera as configurações de uma TV da propriedade' },
  { command: '/uniforme', description: 'Abre o menu de seleção de roupas' },
  { command: '/usaruniforme', description: 'Usa um uniforme pré-definido' },
  { command: '/usuario (usuário)', description: 'Visualiza as informações de um usuário' },
  { command: '/valugar', description: 'Aluga um veículo de emprego' },
  { command: '/vchave', description: 'Cria uma chave cópia de um veículo' },
  { command: '/vcolocarpregos', description: 'Coloca um tapete de pregos no porta-malas de um veículo' },
  { command: '/veiculos', description: 'Abre o painel de gerenciamento de veículos' },
  { command: '/velmax (velocidade)', description: 'Define a velocidade máxima de um veículo' },
  { command: '/vestacionar', description: 'Estaciona um veículo' },
  { command: '/vfechadura', description: 'Altera a fechadura de um veículo' },
  { command: '/vflip (veículo)', description: 'Descapota um veículo' },
  { command: '/vlista', description: 'Mostra seus veículos' },
  { command: '/vpegarpregos', description: 'Pega um tapete de pregos do porta-malas de um veículo' },
  { command: '/vporta (porta [1-4])', description: 'Abre/fecha a porta de um veículo' },
  { command: '/vtransferir (ID ou nome)', description: 'Transfere um veículo para outro personagem' },
  { command: '/vvender (ID ou nome) (valor)', description: 'Vende um veículo para outro personagem' },
  { command: '/waypoint', description: 'Teleporta até o waypoint marcado no mapa' },
  { command: '/xmr', description: 'Altera as configurações do XMR' },
  { command: '/modoanim', description: 'Edita sua posição/rotação na animação' },
  { command: '/criarapartamento (interior) (valor) (número propriedade mãe) (nome)', description: 'Cria um apartamento' },
  { command: '/cap (interior) (valor) (número propriedade mãe) (nome)', description: 'Cria um apartamento' },
  { command: '/pontos', description: 'Abre o painel de gerenciamento de pontos' },
  { command: '/criarponto (tipo)', description: 'Cria um ponto' },
  { command: '/gps (endereço)', description: 'Busca a localização de uma propriedade' },
  { command: '/temperatura', description: 'Visualiza a temperatura e o clima atual' },
  { command: '/incendios', description: 'Abre o painel de gerenciamento de incêndios' },
  { command: '/mascara', description: 'Coloca/remove a máscara' },
  { command: '/inventario', description: 'Abre o inventário' },
  { command: '/inv', description: 'Abre o inventário' },
  { command: '/ploc', description: 'Atualiza a localização da sua unidade' },
  { command: '/ps (status)', description: 'Atualiza o status da sua unidade' },
  { command: '/setfaccao (ID ou nome) (nome da facção)', description: 'Define a facção de um jogador' },
  { command: '/deletarsangue (distância)', description: 'Deleta todas as amostras de sangue do chão na distância informada' },
  { command: '/deletarcapsulas (distância)', description: 'Deleta todas as cápsulas do chão na distância informada' },
  { command: '/ftow', description: 'Respawna todos os veículos da facção sem ocupantes' },
  { command: '/convidar (ID ou nome)', description: 'Convida um jogador para sua facção' },
  { command: '/irls', description: 'Vai para o spawn inicial' },
  { command: '/aspawn (placa)', description: 'Spawna um veículo' },
  { command: '/fixloc', description: 'Corrige sua localização dentro de uma propriedade' },
  { command: '/eprop (número)', description: 'Edita uma propriedade' },
  { command: '/irprop (número)', description: 'Vai para uma propriedade' },
  { command: '/delprop (número)', description: 'Deleta uma propriedade' },
  { command: '/rdonoprop (número)', description: 'Remove o dono da propriedade' },
  { command: '/entradasprop (número)', description: 'Edita as entradas de uma propriedade' },
  { command: '/delponto', description: 'Deleta o ponto mais próximo' },
  { command: '/outfits', description: 'Abre a interface de outfits' },
  { command: '/outfit (slot)', description: 'Altera o outfit em uso' },
  { command: '/corrigirvw', description: 'Corrige seu VW' },
  { command: '/setvw (ID ou nome) (VW)', description: 'Define o VW de um jogador' },
  { command: '/atributos', description: 'Define os seus atributos' },
  { command: '/examinar', description: 'Visualiza os atributos de um personagem próximo' },
  { command: '/idade (ID ou nome) (idade)', description: 'Altera a idade de um personagem' },
  { command: '/anrp (mensagem)', description: 'Envia um anúncio de roleplay' },
  { command: '/supporters', description: 'Exibe os supporters do servidor' },
  { command: '/debug', description: 'Habilita a visão de depuração' },
  { command: '/rtempo', description: 'Remove o tempo e ativa a sincronização automática' },
  { command: '/pegarneve', description: 'Pega uma bola de neve do chão' },
  { command: '/enome (ID ou nome) (novo nome)', description: 'Define o nome temporário de um jogador' },
  { command: '/audios', description: 'Lista os áudios ativos' },
  { command: '/congelar (ID ou nome)', description: 'Congela/descongela um jogador' },
  { command: '/fixpos (nome do personagem)', description: 'Corrige a posição do personagem para evitar crash ao logar' },
  { command: '/vtrancar', description: 'Tranca/destranca um veículo' },
  { command: '/vida (ID ou nome) (vida)', description: 'Altera a vida de um jogador' },
  { command: '/colete (ID ou nome) (colete)', description: 'Altera o colete de um jogador' },
  { command: '/vertela (ID ou nome)', description: 'Visualiza informações da tela de um jogador' },
  { command: '/blocktogstaff', description: 'Bloqueia/desbloqueia os togs administrativos' },
  { command: '/cabelo', description: 'Ativa/desativa o cabelo' },
  { command: '/anametag', description: 'Ativa/desativa a nametag à distância' },
  { command: '/skin (ID ou nome) (skin)', description: 'Altera a skin de um jogador' },
  { command: '/ar (ID)', description: 'Atende um report' },
  { command: '/listareport', description: 'Lista os reports pendentes' },
  { command: '/cancelarsos', description: 'Cancela o seu SOS' },
  { command: '/cancelarreport', description: 'Cancela o seu report' },
  { command: '/celulares', description: 'Lista os seus números' },
  { command: '/transferir (conta bancária) (valor) (descrição)', description: 'Transfere o valor para uma conta bancária' },
  { command: '/fixinvi', description: 'Corrige a invisibilidade do seu personagem' },
  { command: '/checarafk (ID ou nome)', description: 'Checa se o jogador está AFK' },
  { command: '/afks', description: 'Lista os jogadores que estão AFK' },
  { command: '/lobby', description: 'Lista os jogadores que não estão spawnados' },
  { command: '/mascarados', description: 'Lista os jogadores mascarados' },
  { command: '/nome (ID ou nome) (novo nome)', description: 'Altera o nome permanente de um jogador' },
]